# Magnetospheric Multiscale (MMS) Project Configuration
name = "Magnetospheric Multiscale"

[metadata]
abbreviation = "MMS"

# Instruments
[instruments.fpi]
name = "Fast Plasma Investigation"
datasets = ["fpi_moms"]

[instruments.fgm]
name = "Fluxgate Magnetometer"

[instruments.scm]
name = "Search-coil Magnetometer"

[instruments.edp]
name = "Electric Field Double Probe"

[instruments.edi]
name = "Electron Drift Instrument"

[instruments.feeps]
name = "Fly's Eye Energetic Particle Sensor"

[instruments.eis]
name = "Energetic Ion Spectrometer"

[instruments.hpca]
name = "Hot Plasma Composition Analyzer"

# FPI Dataset Configuration
[datasets.fpi_moms]
format = "MMS{probe}_FPI_{data_rate}_L2_{data_type}-MOMS"

[datasets.fpi_moms.metadata]
probes = [1, 2, 3, 4]
data_rates = ["fast", "brst"]
data_types = ["des", "dis"]

[datasets.fpi_moms.parameters]
numberdensity = "mms{probe}_{data_type}_numberdensity_{data_rate}"
bulkv_gse = "mms{probe}_{data_type}_bulkv_gse_{data_rate}"
temppara = "mms{probe}_{data_type}_temppara_{data_rate}"
tempperp = "mms{probe}_{data_type}_tempperp_{data_rate}"
energyspectr_omni = "mms{probe}_{data_type}_energyspectr_omni_{data_rate}"
# energyspectr_perp = "mms{probe}_{data_type}_energyspectr_perp_{data_rate}"
# energyspectr_par = "mms{probe}_{data_type}_energyspectr_par_{data_rate}"
# energyspectr_anti = "mms{probe}_{data_type}_energyspectr_anti_{data_rate}"
# mms2_des_energyspectr_perp_brst
