name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/**"
      - "Project.toml"
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy Documenter.jl docs
        uses: JuliaSpacePhysics/actions/DocsDocumenter@main
        env:
          SPEASY_CORE_DISABLED_PROVIDERS: csa,amda
